/**
 * This code was generated by Diez version 10.6.0.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */
import { Color, File, Font, Image, Typograph } from "@diez/prefabs";

const bXvdlTokensColors = {
    alertYellowAlert: Color.rgba(255, 226, 124, 1),
    alertYellowAir: Color.rgba(255, 232, 150, 1),
    greedBook: Color.rgba(64, 141, 92, 1),
    greedLight: Color.rgba(239, 250, 243, 1),
    greedAlert: Color.rgba(125, 213, 157, 1),
    alertYellowNice: Color.rgba(255, 238, 177, 1),
    alertYellowCloud: Color.rgba(255, 246, 216, 1),
    alertYellowBlank: Color.rgba(255, 252, 242, 1),
    alertYellowBrown: Color.rgba(224, 195, 92, 1),
    alertYellowGold: Color.rgba(153, 136, 75, 1),
    alertYellowGo: Color.rgba(102, 90, 50, 1),
    redAlertApp: Color.rgba(253, 38, 38, 1),
    redLand: Color.rgba(254, 190, 190, 1),
    redClean: Color.rgba(255, 233, 233, 1),
    redMedium: Color.rgba(254, 103, 103, 1),
    redNice: Color.rgba(254, 146, 146, 1),
    grisOne: Color.rgba(51, 51, 51, 1),
    grisYou: Color.rgba(229, 229, 229, 1),
    grisPress: Color.rgba(77, 77, 77, 1),
    grisOn: Color.rgba(251, 251, 251, 1),
    redBlood: Color.rgba(177, 27, 27, 1),
    redUp: Color.rgba(126, 19, 19, 1),
    redBlack: Color.rgba(76, 11, 11, 1),
    blackTotal: Color.rgba(33, 33, 33, 1),
    grisOne1: Color.rgba(51, 51, 51, 1),
    grisPress1: Color.rgba(77, 77, 77, 1),
    grisMistery: Color.rgba(102, 102, 102, 1),
    grisPlay: Color.rgba(128, 128, 128, 1),
    grisTime: Color.rgba(179, 179, 179, 1),
    grisMe: Color.rgba(204, 204, 204, 1),
    grisYou1: Color.rgba(229, 229, 229, 1),
    grisUp: Color.rgba(246, 246, 246, 1),
    blancoPress: Color.rgba(255, 255, 255, 1),
    grisOn1: Color.rgba(251, 251, 251, 1),
    naranjoMiles: Color.rgba(255, 139, 87, 1),
    lightWay: Color.rgba(39, 166, 229, 1),
    lightIce: Color.rgba(85, 199, 255, 1),
    lightDrop: Color.rgba(107, 206, 255, 1),
    lightGive: Color.rgba(30, 129, 178, 1),
    lightDream: Color.rgba(128, 213, 255, 1),
    lightWell: Color.rgba(26, 111, 153, 1),
    lightOur: Color.rgba(21, 92, 128, 1),
    lightSea: Color.rgba(17, 74, 102, 1),
    lightEasy: Color.rgba(191, 234, 255, 1),
    lightThin: Color.rgba(213, 241, 255, 1),
    lightDay: Color.rgba(234, 248, 255, 1),
    lightOnly: Color.rgba(4, 18, 25, 1),
    blueFlip: Color.rgba(46, 89, 229, 1),
    naranjoFull: Color.rgba(229, 113, 61, 1),
    naranjoGo: Color.rgba(143, 71, 38, 1),
    naranjoSpace: Color.rgba(153, 76, 41, 1),
    naranjoNovel: Color.rgba(102, 50, 27, 1),
    naranjoWine: Color.rgba(76, 38, 20, 1),
    pinkBlood: Color.rgba(25, 13, 7, 1),
    pinkGum: Color.rgba(255, 152, 105, 1),
    blueRock: Color.rgba(92, 130, 255, 1),
    bluePlace: Color.rgba(41, 79, 204, 1),
    blueFun: Color.rgba(112, 146, 255, 1),
    blueMoon: Color.rgba(41, 79, 204, 1),
    pinkFly: Color.rgba(255, 178, 143, 1),
    pinkRubber: Color.rgba(255, 190, 161, 1),
    naranjoElastic: Color.rgba(255, 203, 180, 1),
    naranjoCandy: Color.rgba(255, 216, 199, 1),
    naranjoRose: Color.rgba(255, 229, 218, 1),
    naranjoBlank: Color.rgba(255, 233, 241, 1),
    blueAir: Color.rgba(133, 161, 255, 1),
    blueSoft: Color.rgba(153, 177, 255, 1),
    blueNew: Color.rgba(173, 193, 255, 1),
    blueShine: Color.rgba(194, 208, 255, 1),
    blueClear: Color.rgba(214, 224, 255, 1),
    blueCloud: Color.rgba(235, 239, 255, 1),
    blueCross: Color.rgba(31, 59, 153, 1),
    bluePoint: Color.rgba(25, 49, 128, 1),
    blueClip: Color.rgba(20, 40, 102, 1),
    blueTea: Color.rgba(15, 30, 76, 1),
    naranjoSuperapp: Color.rgba(255, 126, 68, 1),
    orangeSummer: Color.rgba(252, 190, 105, 1),
    orangeTry: Color.rgba(227, 171, 94, 1),
    orangeFruit: Color.rgba(252, 196, 120, 1),
    orangePyme: Color.rgba(202, 152, 84, 1),
    orangeNow: Color.rgba(253, 203, 135, 1),
    orangeBox: Color.rgba(176, 133, 73, 1),
    orangeMake: Color.rgba(253, 210, 150, 1),
    orangeTruck: Color.rgba(151, 114, 63, 1),
    orangeTravel: Color.rgba(253, 216, 165, 1),
    orangeGrow: Color.rgba(101, 76, 42, 1),
    orangeSend: Color.rgba(254, 236, 210, 1),
    orangeState: Color.rgba(50, 38, 21, 1),
    orangeSkin: Color.rgba(254, 242, 225, 1),
    blueSuperapp: Color.rgba(51, 99, 255, 1)
};

export const bXvdlTokensFonts = {
    RobotoLight: {
        Regular: Font.fromFile("assets/BXvdlTokens.figma.contents/fonts/Roboto-Light.ttf")
    },
    Roboto: {
        Regular: Font.fromFile("assets/BXvdlTokens.figma.contents/fonts/Roboto-Regular.ttf")
    }
};

const bXvdlTokensTypography = {
    caption: new Typograph({ letterSpacing: 0, fontSize: 10, lineHeight: 11.71875, color: Color.rgba(15, 51, 101, 1), font: bXvdlTokensFonts.RobotoLight.Regular }),
    grisUp: new Typograph({ letterSpacing: 0.42, fontSize: 14, lineHeight: 17.220001220703125, color: Color.rgba(51, 51, 51, 1), font: bXvdlTokensFonts.Roboto.Regular }),
    paragraph1App: new Typograph({ letterSpacing: 0.42, fontSize: 14, lineHeight: 20.30000114440918, color: Color.rgba(246, 246, 246, 1), font: new Font({ name: "Lato-Regular" }) }),
    paragraph1: new Typograph({ letterSpacing: 0.42, fontSize: 14, lineHeight: 22.1200008392334, color: Color.rgba(246, 246, 246, 1), font: bXvdlTokensFonts.Roboto.Regular })
};

export const bXvdlTokensImagesFiles = {
    blueSuperapp: new File({ src: "assets/BXvdlTokens.figma.contents/images/BlueSuperapp.png" }),
    blueSuperapp2x: new File({ src: "assets/BXvdlTokens.figma.contents/images/BlueSuperapp@2x.png" }),
    blueSuperapp3x: new File({ src: "assets/BXvdlTokens.figma.contents/images/BlueSuperapp@3x.png" }),
    blueSuperapp4x: new File({ src: "assets/BXvdlTokens.figma.contents/images/BlueSuperapp@4x.png" }),
    palette: new File({ src: "assets/BXvdlTokens.figma.contents/images/Palette.png" }),
    palette2x: new File({ src: "assets/BXvdlTokens.figma.contents/images/Palette@2x.png" }),
    palette3x: new File({ src: "assets/BXvdlTokens.figma.contents/images/Palette@3x.png" }),
    palette4x: new File({ src: "assets/BXvdlTokens.figma.contents/images/Palette@4x.png" })
};

/**
 * This is provided for backward compatibility, please use `bXvdlTokensImagesFiles` instead.
 * @deprecated
 */
export const bXvdlTokensComponentsFiles = bXvdlTokensImagesFiles;

export const bXvdlTokensImages = {
    blueSuperapp: Image.responsive("assets/BXvdlTokens.figma.contents/images/BlueSuperapp.png", 181, 100),
    palette: Image.responsive("assets/BXvdlTokens.figma.contents/images/Palette.png", 2124, 1131)
};

/**
 * This is provided for backward compatibility, please use `bXvdlTokensImages` instead.
 * @deprecated
 */
export const bXvdlTokensComponents = bXvdlTokensImages;

export const bXvdlTokensTokens = {
    colors: bXvdlTokensColors,
    typography: bXvdlTokensTypography
};
