/**
 * This code was generated by Diez version 10.6.0.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */
import { Color } from "@diez/prefabs";

const pocColoresColors = {
    primary: Color.rgba(77, 152, 208, 1),
    warning: Color.rgba(254, 180, 38, 1),
    secondary: Color.rgba(232, 97, 4, 1),
    danger: Color.rgba(186, 45, 53, 1),
    dark: Color.rgba(82, 65, 100, 1),
    gray: Color.rgba(189, 189, 189, 1)
};

export const pocColoresTokens = {
    colors: pocColoresColors
};
