"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.pocColoresTokens = void 0;
/**
 * This code was generated by Diez version 10.6.0.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */
const prefabs_1 = require("@diez/prefabs");
const pocColoresColors = {
    primary: prefabs_1.Color.rgba(77, 152, 208, 1),
    warning: prefabs_1.Color.rgba(254, 180, 38, 1),
    secondary: prefabs_1.Color.rgba(232, 97, 4, 1),
    danger: prefabs_1.Color.rgba(186, 45, 53, 1),
    dark: prefabs_1.Color.rgba(82, 65, 100, 1),
    gray: prefabs_1.Color.rgba(189, 189, 189, 1)
};
exports.pocColoresTokens = {
    colors: pocColoresColors
};
//# sourceMappingURL=pocColores.figma.js.map